services:
  - type: web
    name: realtime-websocket-chat
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://fsd-practical-9-vercel-o4g1.vercel.app/
    healthCheckPath: /
